name: "projectNodeJs1"

services:
  database:
    image: mariadb:11
    ports:
      - "3309:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'express'


  express:
    image: node:23
    ports:
      - "8090:3000"
    volumes:
      - ./app:/app
    command: 'sh -c "node /app/server.js"'

